export const SET_DISHES = "SET_DISHES";

export const ADD_DISH = "ADD_DISH";

export const PURCHASE_ORDER_SUCCESS = "PURCHASE_ORDER_SUCCESS";
export const PURCHASE_ORDER_FAILURE = "PURCHASE_ORDER_FAILURE";
